### ISSUE TITLE
Configure SSL/TLS for TBMQ

### ISSUE THREAD

**Issue by grantapeck** [thingsboard/tbmq#173]
**Component**

* Installation

**Description**
Configuring SSL from port 80 to 443 and passing to proxy via 8083 results in 404 response or "not authorised" when logging in.
I am using NGINX. Should this work? Should I be using HAProxy instead?

**Environment**

* OS:  ubuntu 24.04 lts on AWS
* TBMQ: version release-1.4.0 as available on your site
* BRAVE Version 1.71.114 Chromium: 130.0.6723.58 (Official Build) (64-bit)](https://brave.com/latest/)

Thanks in anticipation.
Grant

**Comment by dmytro-landiak** [comment]
Hi @grantapeck,

Thank you for reaching out. In general, it should be possible to configure SSL from port 80 to 443 and pass it through a proxy via port 8083 using NGINX. However, we have not conducted any specific tests with NGINX in this configuration, so I can't provide concrete guidance on this setup.

That said, we have tested a similar setup using HAProxy, which worked well for us. You might want to consider using HAProxy instead. Here’s a link to more details on configuring this setup with HAProxy: https://github.com/thingsboard/tbmq/tree/main/docker. 

Please feel free to reach out if you have any further questions or need additional assistance.

Best regards!

**Comment by grantapeck** [comment]
Hey @dmytro-landiak,

Thank your for your response. 

I'm new to linux, server admin, and definitely all the things thingsboard so my apologies for this question. . . effectively I'm a newbie.

Will this procedure for installing HAProxy work on the tbmq server: https://thingsboard.io/docs/user-guide/install/pe/add-haproxy-ubuntu/ so the ui is redirected across https? 

I sense I'm missing the point.

I have successfully used nginx on the thingsboard (I am using two different servers) and it's working aok.

Thanks in anticipation.
Grant

**Comment by dmytro-landiak** [comment]
hey @grantapeck!

Yes, please follow the link I provided to set up HAProxy. However, keep in mind that the [link](https://thingsboard.io/docs/user-guide/install/pe/add-haproxy-ubuntu/) covers installing HAProxy directly on an Ubuntu machine rather than in a Docker container.

Since TBMQ is deployed in Docker, it’s generally recommended to install HAProxy in Docker as well for consistency and easier management. You can use the `.cfg` file in the TBMQ repository as a starting point, as it’s tailored for TBMQ’s specific configurations.

Let me know if you need any further guidance!
